//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppQuanLy.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DangNhapAppWinForm", ReplyAction="*")]
        AppQuanLy.ServiceReference1.DangNhapAppWinFormResponse DangNhapAppWinForm(AppQuanLy.ServiceReference1.DangNhapAppWinFormRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DangNhapAppWinForm", ReplyAction="*")]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.DangNhapAppWinFormResponse> DangNhapAppWinFormAsync(AppQuanLy.ServiceReference1.DangNhapAppWinFormRequest request);
        
        // CODEGEN: Generating message contract since element name GetListUser_BEResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListUser_BE", ReplyAction="*")]
        AppQuanLy.ServiceReference1.GetListUser_BEResponse GetListUser_BE(AppQuanLy.ServiceReference1.GetListUser_BERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListUser_BE", ReplyAction="*")]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.GetListUser_BEResponse> GetListUser_BEAsync(AppQuanLy.ServiceReference1.GetListUser_BERequest request);
        
        // CODEGEN: Generating message contract since element name json from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditUser_BE", ReplyAction="*")]
        AppQuanLy.ServiceReference1.EditUser_BEResponse EditUser_BE(AppQuanLy.ServiceReference1.EditUser_BERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditUser_BE", ReplyAction="*")]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.EditUser_BEResponse> EditUser_BEAsync(AppQuanLy.ServiceReference1.EditUser_BERequest request);
        
        // CODEGEN: Generating message contract since element name json from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser_BE", ReplyAction="*")]
        AppQuanLy.ServiceReference1.AddUser_BEResponse AddUser_BE(AppQuanLy.ServiceReference1.AddUser_BERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser_BE", ReplyAction="*")]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.AddUser_BEResponse> AddUser_BEAsync(AppQuanLy.ServiceReference1.AddUser_BERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser_BE", ReplyAction="*")]
        void DeleteUser_BE(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser_BE", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteUser_BEAsync(int id);
        
        // CODEGEN: Generating message contract since element name GetListHotel_BEResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListHotel_BE", ReplyAction="*")]
        AppQuanLy.ServiceReference1.GetListHotel_BEResponse GetListHotel_BE(AppQuanLy.ServiceReference1.GetListHotel_BERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListHotel_BE", ReplyAction="*")]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.GetListHotel_BEResponse> GetListHotel_BEAsync(AppQuanLy.ServiceReference1.GetListHotel_BERequest request);
        
        // CODEGEN: Generating message contract since element name json from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddHotel_BE", ReplyAction="*")]
        AppQuanLy.ServiceReference1.AddHotel_BEResponse AddHotel_BE(AppQuanLy.ServiceReference1.AddHotel_BERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddHotel_BE", ReplyAction="*")]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.AddHotel_BEResponse> AddHotel_BEAsync(AppQuanLy.ServiceReference1.AddHotel_BERequest request);
        
        // CODEGEN: Generating message contract since element name json from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditHotel_BE", ReplyAction="*")]
        AppQuanLy.ServiceReference1.EditHotel_BEResponse EditHotel_BE(AppQuanLy.ServiceReference1.EditHotel_BERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditHotel_BE", ReplyAction="*")]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.EditHotel_BEResponse> EditHotel_BEAsync(AppQuanLy.ServiceReference1.EditHotel_BERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteHotel_BE", ReplyAction="*")]
        void DeleteHotel_BE(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteHotel_BE", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteHotel_BEAsync(int id);
        
        // CODEGEN: Generating message contract since element name GetListHomestay_BEResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListHomestay_BE", ReplyAction="*")]
        AppQuanLy.ServiceReference1.GetListHomestay_BEResponse GetListHomestay_BE(AppQuanLy.ServiceReference1.GetListHomestay_BERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListHomestay_BE", ReplyAction="*")]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.GetListHomestay_BEResponse> GetListHomestay_BEAsync(AppQuanLy.ServiceReference1.GetListHomestay_BERequest request);
        
        // CODEGEN: Generating message contract since element name json from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddHomestay_BE", ReplyAction="*")]
        AppQuanLy.ServiceReference1.AddHomestay_BEResponse AddHomestay_BE(AppQuanLy.ServiceReference1.AddHomestay_BERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddHomestay_BE", ReplyAction="*")]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.AddHomestay_BEResponse> AddHomestay_BEAsync(AppQuanLy.ServiceReference1.AddHomestay_BERequest request);
        
        // CODEGEN: Generating message contract since element name json from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditHomestay_BE", ReplyAction="*")]
        AppQuanLy.ServiceReference1.EditHomestay_BEResponse EditHomestay_BE(AppQuanLy.ServiceReference1.EditHomestay_BERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditHomestay_BE", ReplyAction="*")]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.EditHomestay_BEResponse> EditHomestay_BEAsync(AppQuanLy.ServiceReference1.EditHomestay_BERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteHomestay_BE", ReplyAction="*")]
        void DeleteHomestay_BE(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteHomestay_BE", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteHomestay_BEAsync(int id);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListBooking_BE", ReplyAction="*")]
        AppQuanLy.ServiceReference1.GetListBooking_BEResponse GetListBooking_BE(AppQuanLy.ServiceReference1.GetListBooking_BERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListBooking_BE", ReplyAction="*")]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.GetListBooking_BEResponse> GetListBooking_BEAsync(AppQuanLy.ServiceReference1.GetListBooking_BERequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DangNhapAppWinFormRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DangNhapAppWinForm", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.DangNhapAppWinFormRequestBody Body;
        
        public DangNhapAppWinFormRequest() {
        }
        
        public DangNhapAppWinFormRequest(AppQuanLy.ServiceReference1.DangNhapAppWinFormRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DangNhapAppWinFormRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public DangNhapAppWinFormRequestBody() {
        }
        
        public DangNhapAppWinFormRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DangNhapAppWinFormResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DangNhapAppWinFormResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.DangNhapAppWinFormResponseBody Body;
        
        public DangNhapAppWinFormResponse() {
        }
        
        public DangNhapAppWinFormResponse(AppQuanLy.ServiceReference1.DangNhapAppWinFormResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DangNhapAppWinFormResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DangNhapAppWinFormResult;
        
        public DangNhapAppWinFormResponseBody() {
        }
        
        public DangNhapAppWinFormResponseBody(string DangNhapAppWinFormResult) {
            this.DangNhapAppWinFormResult = DangNhapAppWinFormResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListUser_BERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListUser_BE", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.GetListUser_BERequestBody Body;
        
        public GetListUser_BERequest() {
        }
        
        public GetListUser_BERequest(AppQuanLy.ServiceReference1.GetListUser_BERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListUser_BERequestBody {
        
        public GetListUser_BERequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListUser_BEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListUser_BEResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.GetListUser_BEResponseBody Body;
        
        public GetListUser_BEResponse() {
        }
        
        public GetListUser_BEResponse(AppQuanLy.ServiceReference1.GetListUser_BEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListUser_BEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetListUser_BEResult;
        
        public GetListUser_BEResponseBody() {
        }
        
        public GetListUser_BEResponseBody(string GetListUser_BEResult) {
            this.GetListUser_BEResult = GetListUser_BEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditUser_BERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditUser_BE", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.EditUser_BERequestBody Body;
        
        public EditUser_BERequest() {
        }
        
        public EditUser_BERequest(AppQuanLy.ServiceReference1.EditUser_BERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditUser_BERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_old;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string json;
        
        public EditUser_BERequestBody() {
        }
        
        public EditUser_BERequestBody(int id_old, string json) {
            this.id_old = id_old;
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditUser_BEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditUser_BEResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.EditUser_BEResponseBody Body;
        
        public EditUser_BEResponse() {
        }
        
        public EditUser_BEResponse(AppQuanLy.ServiceReference1.EditUser_BEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditUser_BEResponseBody {
        
        public EditUser_BEResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUser_BERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser_BE", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.AddUser_BERequestBody Body;
        
        public AddUser_BERequest() {
        }
        
        public AddUser_BERequest(AppQuanLy.ServiceReference1.AddUser_BERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUser_BERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        public AddUser_BERequestBody() {
        }
        
        public AddUser_BERequestBody(string json) {
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUser_BEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser_BEResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.AddUser_BEResponseBody Body;
        
        public AddUser_BEResponse() {
        }
        
        public AddUser_BEResponse(AppQuanLy.ServiceReference1.AddUser_BEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddUser_BEResponseBody {
        
        public AddUser_BEResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListHotel_BERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListHotel_BE", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.GetListHotel_BERequestBody Body;
        
        public GetListHotel_BERequest() {
        }
        
        public GetListHotel_BERequest(AppQuanLy.ServiceReference1.GetListHotel_BERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListHotel_BERequestBody {
        
        public GetListHotel_BERequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListHotel_BEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListHotel_BEResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.GetListHotel_BEResponseBody Body;
        
        public GetListHotel_BEResponse() {
        }
        
        public GetListHotel_BEResponse(AppQuanLy.ServiceReference1.GetListHotel_BEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListHotel_BEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetListHotel_BEResult;
        
        public GetListHotel_BEResponseBody() {
        }
        
        public GetListHotel_BEResponseBody(string GetListHotel_BEResult) {
            this.GetListHotel_BEResult = GetListHotel_BEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddHotel_BERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddHotel_BE", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.AddHotel_BERequestBody Body;
        
        public AddHotel_BERequest() {
        }
        
        public AddHotel_BERequest(AppQuanLy.ServiceReference1.AddHotel_BERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddHotel_BERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        public AddHotel_BERequestBody() {
        }
        
        public AddHotel_BERequestBody(string json) {
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddHotel_BEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddHotel_BEResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.AddHotel_BEResponseBody Body;
        
        public AddHotel_BEResponse() {
        }
        
        public AddHotel_BEResponse(AppQuanLy.ServiceReference1.AddHotel_BEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddHotel_BEResponseBody {
        
        public AddHotel_BEResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditHotel_BERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditHotel_BE", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.EditHotel_BERequestBody Body;
        
        public EditHotel_BERequest() {
        }
        
        public EditHotel_BERequest(AppQuanLy.ServiceReference1.EditHotel_BERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditHotel_BERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_old;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string json;
        
        public EditHotel_BERequestBody() {
        }
        
        public EditHotel_BERequestBody(int id_old, string json) {
            this.id_old = id_old;
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditHotel_BEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditHotel_BEResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.EditHotel_BEResponseBody Body;
        
        public EditHotel_BEResponse() {
        }
        
        public EditHotel_BEResponse(AppQuanLy.ServiceReference1.EditHotel_BEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditHotel_BEResponseBody {
        
        public EditHotel_BEResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListHomestay_BERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListHomestay_BE", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.GetListHomestay_BERequestBody Body;
        
        public GetListHomestay_BERequest() {
        }
        
        public GetListHomestay_BERequest(AppQuanLy.ServiceReference1.GetListHomestay_BERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListHomestay_BERequestBody {
        
        public GetListHomestay_BERequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListHomestay_BEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListHomestay_BEResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.GetListHomestay_BEResponseBody Body;
        
        public GetListHomestay_BEResponse() {
        }
        
        public GetListHomestay_BEResponse(AppQuanLy.ServiceReference1.GetListHomestay_BEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListHomestay_BEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetListHomestay_BEResult;
        
        public GetListHomestay_BEResponseBody() {
        }
        
        public GetListHomestay_BEResponseBody(string GetListHomestay_BEResult) {
            this.GetListHomestay_BEResult = GetListHomestay_BEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddHomestay_BERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddHomestay_BE", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.AddHomestay_BERequestBody Body;
        
        public AddHomestay_BERequest() {
        }
        
        public AddHomestay_BERequest(AppQuanLy.ServiceReference1.AddHomestay_BERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddHomestay_BERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        public AddHomestay_BERequestBody() {
        }
        
        public AddHomestay_BERequestBody(string json) {
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddHomestay_BEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddHomestay_BEResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.AddHomestay_BEResponseBody Body;
        
        public AddHomestay_BEResponse() {
        }
        
        public AddHomestay_BEResponse(AppQuanLy.ServiceReference1.AddHomestay_BEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddHomestay_BEResponseBody {
        
        public AddHomestay_BEResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditHomestay_BERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditHomestay_BE", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.EditHomestay_BERequestBody Body;
        
        public EditHomestay_BERequest() {
        }
        
        public EditHomestay_BERequest(AppQuanLy.ServiceReference1.EditHomestay_BERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditHomestay_BERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_old;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string json;
        
        public EditHomestay_BERequestBody() {
        }
        
        public EditHomestay_BERequestBody(int id_old, string json) {
            this.id_old = id_old;
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditHomestay_BEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditHomestay_BEResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.EditHomestay_BEResponseBody Body;
        
        public EditHomestay_BEResponse() {
        }
        
        public EditHomestay_BEResponse(AppQuanLy.ServiceReference1.EditHomestay_BEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditHomestay_BEResponseBody {
        
        public EditHomestay_BEResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListBooking_BERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListBooking_BE", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.GetListBooking_BERequestBody Body;
        
        public GetListBooking_BERequest() {
        }
        
        public GetListBooking_BERequest(AppQuanLy.ServiceReference1.GetListBooking_BERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListBooking_BERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public GetListBooking_BERequestBody() {
        }
        
        public GetListBooking_BERequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListBooking_BEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListBooking_BEResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppQuanLy.ServiceReference1.GetListBooking_BEResponseBody Body;
        
        public GetListBooking_BEResponse() {
        }
        
        public GetListBooking_BEResponse(AppQuanLy.ServiceReference1.GetListBooking_BEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListBooking_BEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetListBooking_BEResult;
        
        public GetListBooking_BEResponseBody() {
        }
        
        public GetListBooking_BEResponseBody(string GetListBooking_BEResult) {
            this.GetListBooking_BEResult = GetListBooking_BEResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : AppQuanLy.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<AppQuanLy.ServiceReference1.WebService1Soap>, AppQuanLy.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppQuanLy.ServiceReference1.DangNhapAppWinFormResponse AppQuanLy.ServiceReference1.WebService1Soap.DangNhapAppWinForm(AppQuanLy.ServiceReference1.DangNhapAppWinFormRequest request) {
            return base.Channel.DangNhapAppWinForm(request);
        }
        
        public string DangNhapAppWinForm(string username, string password) {
            AppQuanLy.ServiceReference1.DangNhapAppWinFormRequest inValue = new AppQuanLy.ServiceReference1.DangNhapAppWinFormRequest();
            inValue.Body = new AppQuanLy.ServiceReference1.DangNhapAppWinFormRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            AppQuanLy.ServiceReference1.DangNhapAppWinFormResponse retVal = ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).DangNhapAppWinForm(inValue);
            return retVal.Body.DangNhapAppWinFormResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.DangNhapAppWinFormResponse> AppQuanLy.ServiceReference1.WebService1Soap.DangNhapAppWinFormAsync(AppQuanLy.ServiceReference1.DangNhapAppWinFormRequest request) {
            return base.Channel.DangNhapAppWinFormAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.DangNhapAppWinFormResponse> DangNhapAppWinFormAsync(string username, string password) {
            AppQuanLy.ServiceReference1.DangNhapAppWinFormRequest inValue = new AppQuanLy.ServiceReference1.DangNhapAppWinFormRequest();
            inValue.Body = new AppQuanLy.ServiceReference1.DangNhapAppWinFormRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).DangNhapAppWinFormAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppQuanLy.ServiceReference1.GetListUser_BEResponse AppQuanLy.ServiceReference1.WebService1Soap.GetListUser_BE(AppQuanLy.ServiceReference1.GetListUser_BERequest request) {
            return base.Channel.GetListUser_BE(request);
        }
        
        public string GetListUser_BE() {
            AppQuanLy.ServiceReference1.GetListUser_BERequest inValue = new AppQuanLy.ServiceReference1.GetListUser_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.GetListUser_BERequestBody();
            AppQuanLy.ServiceReference1.GetListUser_BEResponse retVal = ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).GetListUser_BE(inValue);
            return retVal.Body.GetListUser_BEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.GetListUser_BEResponse> AppQuanLy.ServiceReference1.WebService1Soap.GetListUser_BEAsync(AppQuanLy.ServiceReference1.GetListUser_BERequest request) {
            return base.Channel.GetListUser_BEAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.GetListUser_BEResponse> GetListUser_BEAsync() {
            AppQuanLy.ServiceReference1.GetListUser_BERequest inValue = new AppQuanLy.ServiceReference1.GetListUser_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.GetListUser_BERequestBody();
            return ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).GetListUser_BEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppQuanLy.ServiceReference1.EditUser_BEResponse AppQuanLy.ServiceReference1.WebService1Soap.EditUser_BE(AppQuanLy.ServiceReference1.EditUser_BERequest request) {
            return base.Channel.EditUser_BE(request);
        }
        
        public void EditUser_BE(int id_old, string json) {
            AppQuanLy.ServiceReference1.EditUser_BERequest inValue = new AppQuanLy.ServiceReference1.EditUser_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.EditUser_BERequestBody();
            inValue.Body.id_old = id_old;
            inValue.Body.json = json;
            AppQuanLy.ServiceReference1.EditUser_BEResponse retVal = ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).EditUser_BE(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.EditUser_BEResponse> AppQuanLy.ServiceReference1.WebService1Soap.EditUser_BEAsync(AppQuanLy.ServiceReference1.EditUser_BERequest request) {
            return base.Channel.EditUser_BEAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.EditUser_BEResponse> EditUser_BEAsync(int id_old, string json) {
            AppQuanLy.ServiceReference1.EditUser_BERequest inValue = new AppQuanLy.ServiceReference1.EditUser_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.EditUser_BERequestBody();
            inValue.Body.id_old = id_old;
            inValue.Body.json = json;
            return ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).EditUser_BEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppQuanLy.ServiceReference1.AddUser_BEResponse AppQuanLy.ServiceReference1.WebService1Soap.AddUser_BE(AppQuanLy.ServiceReference1.AddUser_BERequest request) {
            return base.Channel.AddUser_BE(request);
        }
        
        public void AddUser_BE(string json) {
            AppQuanLy.ServiceReference1.AddUser_BERequest inValue = new AppQuanLy.ServiceReference1.AddUser_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.AddUser_BERequestBody();
            inValue.Body.json = json;
            AppQuanLy.ServiceReference1.AddUser_BEResponse retVal = ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).AddUser_BE(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.AddUser_BEResponse> AppQuanLy.ServiceReference1.WebService1Soap.AddUser_BEAsync(AppQuanLy.ServiceReference1.AddUser_BERequest request) {
            return base.Channel.AddUser_BEAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.AddUser_BEResponse> AddUser_BEAsync(string json) {
            AppQuanLy.ServiceReference1.AddUser_BERequest inValue = new AppQuanLy.ServiceReference1.AddUser_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.AddUser_BERequestBody();
            inValue.Body.json = json;
            return ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).AddUser_BEAsync(inValue);
        }
        
        public void DeleteUser_BE(int id) {
            base.Channel.DeleteUser_BE(id);
        }
        
        public System.Threading.Tasks.Task DeleteUser_BEAsync(int id) {
            return base.Channel.DeleteUser_BEAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppQuanLy.ServiceReference1.GetListHotel_BEResponse AppQuanLy.ServiceReference1.WebService1Soap.GetListHotel_BE(AppQuanLy.ServiceReference1.GetListHotel_BERequest request) {
            return base.Channel.GetListHotel_BE(request);
        }
        
        public string GetListHotel_BE() {
            AppQuanLy.ServiceReference1.GetListHotel_BERequest inValue = new AppQuanLy.ServiceReference1.GetListHotel_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.GetListHotel_BERequestBody();
            AppQuanLy.ServiceReference1.GetListHotel_BEResponse retVal = ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).GetListHotel_BE(inValue);
            return retVal.Body.GetListHotel_BEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.GetListHotel_BEResponse> AppQuanLy.ServiceReference1.WebService1Soap.GetListHotel_BEAsync(AppQuanLy.ServiceReference1.GetListHotel_BERequest request) {
            return base.Channel.GetListHotel_BEAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.GetListHotel_BEResponse> GetListHotel_BEAsync() {
            AppQuanLy.ServiceReference1.GetListHotel_BERequest inValue = new AppQuanLy.ServiceReference1.GetListHotel_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.GetListHotel_BERequestBody();
            return ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).GetListHotel_BEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppQuanLy.ServiceReference1.AddHotel_BEResponse AppQuanLy.ServiceReference1.WebService1Soap.AddHotel_BE(AppQuanLy.ServiceReference1.AddHotel_BERequest request) {
            return base.Channel.AddHotel_BE(request);
        }
        
        public void AddHotel_BE(string json) {
            AppQuanLy.ServiceReference1.AddHotel_BERequest inValue = new AppQuanLy.ServiceReference1.AddHotel_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.AddHotel_BERequestBody();
            inValue.Body.json = json;
            AppQuanLy.ServiceReference1.AddHotel_BEResponse retVal = ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).AddHotel_BE(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.AddHotel_BEResponse> AppQuanLy.ServiceReference1.WebService1Soap.AddHotel_BEAsync(AppQuanLy.ServiceReference1.AddHotel_BERequest request) {
            return base.Channel.AddHotel_BEAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.AddHotel_BEResponse> AddHotel_BEAsync(string json) {
            AppQuanLy.ServiceReference1.AddHotel_BERequest inValue = new AppQuanLy.ServiceReference1.AddHotel_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.AddHotel_BERequestBody();
            inValue.Body.json = json;
            return ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).AddHotel_BEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppQuanLy.ServiceReference1.EditHotel_BEResponse AppQuanLy.ServiceReference1.WebService1Soap.EditHotel_BE(AppQuanLy.ServiceReference1.EditHotel_BERequest request) {
            return base.Channel.EditHotel_BE(request);
        }
        
        public void EditHotel_BE(int id_old, string json) {
            AppQuanLy.ServiceReference1.EditHotel_BERequest inValue = new AppQuanLy.ServiceReference1.EditHotel_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.EditHotel_BERequestBody();
            inValue.Body.id_old = id_old;
            inValue.Body.json = json;
            AppQuanLy.ServiceReference1.EditHotel_BEResponse retVal = ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).EditHotel_BE(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.EditHotel_BEResponse> AppQuanLy.ServiceReference1.WebService1Soap.EditHotel_BEAsync(AppQuanLy.ServiceReference1.EditHotel_BERequest request) {
            return base.Channel.EditHotel_BEAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.EditHotel_BEResponse> EditHotel_BEAsync(int id_old, string json) {
            AppQuanLy.ServiceReference1.EditHotel_BERequest inValue = new AppQuanLy.ServiceReference1.EditHotel_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.EditHotel_BERequestBody();
            inValue.Body.id_old = id_old;
            inValue.Body.json = json;
            return ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).EditHotel_BEAsync(inValue);
        }
        
        public void DeleteHotel_BE(int id) {
            base.Channel.DeleteHotel_BE(id);
        }
        
        public System.Threading.Tasks.Task DeleteHotel_BEAsync(int id) {
            return base.Channel.DeleteHotel_BEAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppQuanLy.ServiceReference1.GetListHomestay_BEResponse AppQuanLy.ServiceReference1.WebService1Soap.GetListHomestay_BE(AppQuanLy.ServiceReference1.GetListHomestay_BERequest request) {
            return base.Channel.GetListHomestay_BE(request);
        }
        
        public string GetListHomestay_BE() {
            AppQuanLy.ServiceReference1.GetListHomestay_BERequest inValue = new AppQuanLy.ServiceReference1.GetListHomestay_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.GetListHomestay_BERequestBody();
            AppQuanLy.ServiceReference1.GetListHomestay_BEResponse retVal = ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).GetListHomestay_BE(inValue);
            return retVal.Body.GetListHomestay_BEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.GetListHomestay_BEResponse> AppQuanLy.ServiceReference1.WebService1Soap.GetListHomestay_BEAsync(AppQuanLy.ServiceReference1.GetListHomestay_BERequest request) {
            return base.Channel.GetListHomestay_BEAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.GetListHomestay_BEResponse> GetListHomestay_BEAsync() {
            AppQuanLy.ServiceReference1.GetListHomestay_BERequest inValue = new AppQuanLy.ServiceReference1.GetListHomestay_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.GetListHomestay_BERequestBody();
            return ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).GetListHomestay_BEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppQuanLy.ServiceReference1.AddHomestay_BEResponse AppQuanLy.ServiceReference1.WebService1Soap.AddHomestay_BE(AppQuanLy.ServiceReference1.AddHomestay_BERequest request) {
            return base.Channel.AddHomestay_BE(request);
        }
        
        public void AddHomestay_BE(string json) {
            AppQuanLy.ServiceReference1.AddHomestay_BERequest inValue = new AppQuanLy.ServiceReference1.AddHomestay_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.AddHomestay_BERequestBody();
            inValue.Body.json = json;
            AppQuanLy.ServiceReference1.AddHomestay_BEResponse retVal = ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).AddHomestay_BE(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.AddHomestay_BEResponse> AppQuanLy.ServiceReference1.WebService1Soap.AddHomestay_BEAsync(AppQuanLy.ServiceReference1.AddHomestay_BERequest request) {
            return base.Channel.AddHomestay_BEAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.AddHomestay_BEResponse> AddHomestay_BEAsync(string json) {
            AppQuanLy.ServiceReference1.AddHomestay_BERequest inValue = new AppQuanLy.ServiceReference1.AddHomestay_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.AddHomestay_BERequestBody();
            inValue.Body.json = json;
            return ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).AddHomestay_BEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppQuanLy.ServiceReference1.EditHomestay_BEResponse AppQuanLy.ServiceReference1.WebService1Soap.EditHomestay_BE(AppQuanLy.ServiceReference1.EditHomestay_BERequest request) {
            return base.Channel.EditHomestay_BE(request);
        }
        
        public void EditHomestay_BE(int id_old, string json) {
            AppQuanLy.ServiceReference1.EditHomestay_BERequest inValue = new AppQuanLy.ServiceReference1.EditHomestay_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.EditHomestay_BERequestBody();
            inValue.Body.id_old = id_old;
            inValue.Body.json = json;
            AppQuanLy.ServiceReference1.EditHomestay_BEResponse retVal = ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).EditHomestay_BE(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.EditHomestay_BEResponse> AppQuanLy.ServiceReference1.WebService1Soap.EditHomestay_BEAsync(AppQuanLy.ServiceReference1.EditHomestay_BERequest request) {
            return base.Channel.EditHomestay_BEAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.EditHomestay_BEResponse> EditHomestay_BEAsync(int id_old, string json) {
            AppQuanLy.ServiceReference1.EditHomestay_BERequest inValue = new AppQuanLy.ServiceReference1.EditHomestay_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.EditHomestay_BERequestBody();
            inValue.Body.id_old = id_old;
            inValue.Body.json = json;
            return ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).EditHomestay_BEAsync(inValue);
        }
        
        public void DeleteHomestay_BE(int id) {
            base.Channel.DeleteHomestay_BE(id);
        }
        
        public System.Threading.Tasks.Task DeleteHomestay_BEAsync(int id) {
            return base.Channel.DeleteHomestay_BEAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppQuanLy.ServiceReference1.GetListBooking_BEResponse AppQuanLy.ServiceReference1.WebService1Soap.GetListBooking_BE(AppQuanLy.ServiceReference1.GetListBooking_BERequest request) {
            return base.Channel.GetListBooking_BE(request);
        }
        
        public string GetListBooking_BE(string key) {
            AppQuanLy.ServiceReference1.GetListBooking_BERequest inValue = new AppQuanLy.ServiceReference1.GetListBooking_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.GetListBooking_BERequestBody();
            inValue.Body.key = key;
            AppQuanLy.ServiceReference1.GetListBooking_BEResponse retVal = ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).GetListBooking_BE(inValue);
            return retVal.Body.GetListBooking_BEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.GetListBooking_BEResponse> AppQuanLy.ServiceReference1.WebService1Soap.GetListBooking_BEAsync(AppQuanLy.ServiceReference1.GetListBooking_BERequest request) {
            return base.Channel.GetListBooking_BEAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppQuanLy.ServiceReference1.GetListBooking_BEResponse> GetListBooking_BEAsync(string key) {
            AppQuanLy.ServiceReference1.GetListBooking_BERequest inValue = new AppQuanLy.ServiceReference1.GetListBooking_BERequest();
            inValue.Body = new AppQuanLy.ServiceReference1.GetListBooking_BERequestBody();
            inValue.Body.key = key;
            return ((AppQuanLy.ServiceReference1.WebService1Soap)(this)).GetListBooking_BEAsync(inValue);
        }
    }
}
